name: Build Flutter App

on:
  workflow_dispatch:
    inputs:
      company_id:
        description: 'ID da empresa para o flavor'
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest

    # aqui embaixo a permissão correta, dentro do job
    permissions:
      contents: read     # lê o repositório
      actions: write     # disparo programático
      artifacts: write   # permite upload de artifacts

    defaults:
      run:
        working-directory: template_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get pub dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --target lib/main.dart

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
